# Generated by Django 4.1 on 2022-09-08 11:12

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('code', models.IntegerField(verbose_name='رمز')),
                ('expiration_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'رمز یک بار مصرف',
                'verbose_name_plural': 'رمزهای یک بار مصرف',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='پست الکترونیک')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/', verbose_name='عکس')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدیر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال,غیرغعال')),
                ('instagram', models.URLField(blank=True, null=True, unique=True, verbose_name='آیدی اینستاگرام')),
                ('github', models.URLField(blank=True, null=True, unique=True, verbose_name='آدرس گیت هاب')),
                ('linkedin', models.URLField(blank=True, null=True, unique=True, verbose_name='آدرس لینکدین')),
                ('twitter', models.URLField(blank=True, null=True, unique=True, verbose_name='آدرس توییتر')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
            },
        ),
    ]
