# Generated by Django 4.1 on 2022-09-08 11:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, unique=True, verbose_name='عنوان')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='توضیحات فیلم')),
                ('video', models.FileField(upload_to='videos/', verbose_name='ویدیو')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('image', models.ImageField(upload_to='videos/image/', verbose_name='عکس زمینه فیلم')),
                ('views', models.IntegerField(default=0, verbose_name='بازدیدها')),
                ('time', models.IntegerField(default=1, verbose_name='زمان فیلم')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='ادرس اینترنتی')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده ویدیو')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو ها',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribers', models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='اشتراک ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک ها',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک ها ',
                'ordering': ('-created_at',),
            },
        ),
    ]
