# Generated by Django 4.1 on 2022-09-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='desc',
            new_name='description',
        ),
    ]
