# Generated by Django 4.1 on 2022-09-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_ipaddress_remove_video_views_video_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آدرس ای پی ', 'verbose_name_plural': 'آدرس ای پی ها'},
        ),
    ]
