# Generated by Django 4.1 on 2022-09-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_ipaddress_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
    ]
