# Generated by Django 4.1 on 2022-09-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_videoview_video_views_videoview_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoview',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.ipaddress', verbose_name='آدرس ای چی'),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='عنوان ویدیو'),
        ),
    ]
