# Generated by Django 4.1 on 2022-09-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_videoview_ip_address_alter_videoview_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoview',
            options={'verbose_name': ' بازدید ویدیو', 'verbose_name_plural': ' بازدید ویدیو ها'},
        ),
        migrations.AlterField(
            model_name='videoview',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.ipaddress', verbose_name='آدرس ای پی'),
        ),
    ]
