# Generated by Django 4.1 on 2022-09-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(related_name='children_category', to='video.category', verbose_name='زیر دسته'),
        ),
    ]
