# Generated by Django 4.1 on 2022-09-18 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_alter_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
    ]
